# Generated by Django 2.2.5 on 2019-09-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='number_of_songs',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='number_of_Albums',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
