# Generated by Django 2.2.5 on 2019-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190908_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
        migrations.AlterField(
            model_name='album',
            name='date_released',
            field=models.DateField(),
        ),
    ]
