# Generated by Django 2.2.5 on 2019-09-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190908_2351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name',)},
        ),
    ]
