# Generated by Django 2.2.5 on 2019-09-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190908_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title',)},
        ),
    ]
