# Generated by Django 2.2.5 on 2019-09-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190908_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_released',
            field=models.CharField(max_length=100),
        ),
    ]
